// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASMapDRXW9Da-TWKvp3HiaXNWhg-YAFNo',
    appId: '1:926290058864:web:d523094ff805437c5f1eb5',
    messagingSenderId: '926290058864',
    projectId: 'food-api-app-3',
    authDomain: 'food-api-app-3.firebaseapp.com',
    storageBucket: 'food-api-app-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnby-NtluqUSBZzXzUAgZUkoWbDbXd3Gg',
    appId: '1:926290058864:android:cf4cafa79522c1db5f1eb5',
    messagingSenderId: '926290058864',
    projectId: 'food-api-app-3',
    storageBucket: 'food-api-app-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_886sdIMlNloe61GFjXGNpGGoKo9Qd4',
    appId: '1:926290058864:ios:ea7ba02405f4940a5f1eb5',
    messagingSenderId: '926290058864',
    projectId: 'food-api-app-3',
    storageBucket: 'food-api-app-3.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_886sdIMlNloe61GFjXGNpGGoKo9Qd4',
    appId: '1:926290058864:ios:ea7ba02405f4940a5f1eb5',
    messagingSenderId: '926290058864',
    projectId: 'food-api-app-3',
    storageBucket: 'food-api-app-3.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASMapDRXW9Da-TWKvp3HiaXNWhg-YAFNo',
    appId: '1:926290058864:web:3ced2dbd3a787a665f1eb5',
    messagingSenderId: '926290058864',
    projectId: 'food-api-app-3',
    authDomain: 'food-api-app-3.firebaseapp.com',
    storageBucket: 'food-api-app-3.firebasestorage.app',
  );

}